#!/usr/bin/env bash
# Build Moves.app from the SwiftPM target. No Xcode IDE, no xcodebuild —
# just `swift build` + a hand-rolled .app bundle + Apple Dev signing.
#
#   ./build.sh debug       # default
#   ./build.sh release
#
# Env vars (set by Makefile):
#   SIGN_IDENTITY    codesign identity (defaults to ad-hoc "-")
#   PROVISION_PROFILE   optional provisioning profile to embed
set -euo pipefail

CONFIG="${1:-debug}"
APP_NAME="Moves"
BUILD_DIR="build"
APP_PATH="$BUILD_DIR/$APP_NAME.app"
SOURCES_DIR="Sources/$APP_NAME"
INFO_PLIST="$SOURCES_DIR/Resources/Info.plist"
ENTITLEMENTS="$APP_NAME/$APP_NAME.entitlements"
SIGN_IDENTITY="${SIGN_IDENTITY:--}"
PROVISION_PROFILE="${PROVISION_PROFILE:-}"

if [[ "$CONFIG" != "debug" && "$CONFIG" != "release" ]]; then
    echo "✗ unknown configuration: $CONFIG  (expected: debug | release)" >&2
    exit 1
fi

echo "→ swift build -c $CONFIG"
swift build -c "$CONFIG"

BIN_PATH="$(swift build -c "$CONFIG" --show-bin-path)/$APP_NAME"
if [[ ! -x "$BIN_PATH" ]]; then
    echo "✗ binary missing: $BIN_PATH" >&2
    exit 1
fi

echo "→ assembling $APP_PATH"
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

cp "$BIN_PATH" "$APP_PATH/Contents/MacOS/$APP_NAME"
cp "$INFO_PLIST" "$APP_PATH/Contents/Info.plist"

# SwiftPM resource bundles. Any dependency that ships .lproj strings or
# other resources (e.g. KeyboardShortcuts → `KeyboardShortcuts_KeyboardShortcuts.bundle`)
# lands next to the binary at `swift build --show-bin-path`. Without
# copying them into the .app, `Bundle.module` traps with an
# `_assertionFailure` on first access — observed on macOS 14.4 when the
# onboarding sheet renders the hotkey recorder.
#
# SwiftPM (Xcode 26 / Swift 6.3) emits a near-empty Info.plist for these
# resource bundles — just CFBundleDevelopmentRegion. macOS 15+
# `Bundle.init(url:)` accepts that and returns a usable Bundle. macOS 14
# rejects it as "not a bundle" and returns nil, so the SwiftPM-generated
# `Bundle.module` lookup falls through every candidate and fatal-errors.
# Rewrite the Info.plist with the minimum keys macOS 14 requires.
SWIFT_BIN_DIR="$(dirname "$BIN_PATH")"
shopt -s nullglob
for bundle in "$SWIFT_BIN_DIR"/*.bundle; do
    name=$(basename "$bundle")
    # Bundle goes at Contents/Resources/<Name>.bundle. The SwiftPM-
    # generated `Bundle.module` accessor was patched above to look there
    # instead of the .app's top level (codesign won't seal anything at
    # the .app root).
    cp -R "$bundle" "$APP_PATH/Contents/Resources/$name"
    bundle_id="${name%.bundle}"
    # Rewrite Info.plist with the minimum keys macOS 14's `Bundle(path:)`
    # accepts. SwiftPM emits just `CFBundleDevelopmentRegion`; macOS 15+
    # accepts that, macOS 14 rejects the directory as "not a bundle" and
    # returns nil.
    cat > "$APP_PATH/Contents/Resources/$name/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleIdentifier</key>
    <string>org.sockpuppet.Moves.$bundle_id</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$bundle_id</string>
    <key>CFBundlePackageType</key>
    <string>BNDL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
</dict>
</plist>
PLIST
    echo "  + bundled $name in Contents/Resources/ (Info.plist rewritten for macOS 14)"
done
shopt -u nullglob

# App icon. Generated by scripts/make-icon.swift from logo.png. If
# missing, regenerate it: swift scripts/make-icon.swift && \
# iconutil -c icns build/AppIcon.iconset -o build/AppIcon.icns.
ICON_PATH="$BUILD_DIR/AppIcon.icns"
if [[ -f "$ICON_PATH" ]]; then
    cp "$ICON_PATH" "$APP_PATH/Contents/Resources/AppIcon.icns"
else
    echo "⚠ $ICON_PATH missing — app will boot without a custom icon."
fi

# Menu-bar template source. The app loads `logo.png` from Resources at
# launch, runs CIMaskToAlpha over it so the white background becomes
# transparent, and marks the result as a template image so macOS tints
# it for light/dark menu bars.
if [[ -f "logo.png" ]]; then
    cp "logo.png" "$APP_PATH/Contents/Resources/logo.png"
else
    echo "⚠ logo.png missing — menu-bar icon will fall back to the U+265E render."
fi

# PkgInfo is a tiny legacy file LaunchServices still likes.
printf 'APPL????' > "$APP_PATH/Contents/PkgInfo"

if [[ -n "$PROVISION_PROFILE" && -f "$PROVISION_PROFILE" ]]; then
    cp "$PROVISION_PROFILE" "$APP_PATH/Contents/embedded.provisionprofile"
fi

echo "→ codesign (identity: $SIGN_IDENTITY)"

# Nested SwiftPM resource bundles must be signed BEFORE the outer .app
# (innermost-first per Apple's signing rules). Without this, the hardened
# runtime + library validation reject the bundle at load time — the
# `Bundle.module` lookup succeeds but the resource access trips an
# `_assertionFailure` on macOS 14.x. `--deep` would work but is
# deprecated; explicit nested signing is the supported path.
NESTED_SIGN_ARGS=(--force --sign "$SIGN_IDENTITY")
if [[ "$CONFIG" == "release" ]]; then
    NESTED_SIGN_ARGS+=(--options runtime --timestamp)
fi
shopt -s nullglob
for nested in "$APP_PATH"/Contents/Resources/*.bundle; do
    codesign "${NESTED_SIGN_ARGS[@]}" "$nested"
    echo "  + signed $(basename "$nested")"
done
shopt -u nullglob

CODESIGN_ARGS=(--force --sign "$SIGN_IDENTITY")
if [[ "$CONFIG" == "release" ]]; then
    CODESIGN_ARGS+=(--options runtime --timestamp)
fi
if [[ -f "$ENTITLEMENTS" ]]; then
    CODESIGN_ARGS+=(--entitlements "$ENTITLEMENTS")
fi
codesign "${CODESIGN_ARGS[@]}" "$APP_PATH"
codesign --verify --verbose=1 "$APP_PATH"

echo "✓ built $APP_PATH ($CONFIG)"
